# Twitter API Configuration
TWITTER_CLIENT_ID = "RThwTmRvUEtaa0gzdjF4dTF4RzE6MTpjaQ"
TWITTER_CLIENT_SECRET = "dmq6JBhoCKQRCoWvG4yB8eNVHxXbFfR0dlUR8XrFBvRk9Jn6e6"

# API Configuration
FLASK_HOST = "0.0.0.0"
FLASK_PORT = 5000
DEBUG = True

# Movie Prediction Settings
DEFAULT_SAMPLE_SIZE = 100
MAX_TWEETS_PER_REQUEST = 100
SENTIMENT_THRESHOLD = 0.1
